// Clase que representa la información detallada de un país.
class Pais {
  final String oficialName; // Nombre oficial del país.
  final String name; // Nombre del país.
  final String flag; // Bandera del país.
  final String code; // Código del país.
  final int id; // Identificador del país.
  final List<String> languages; // Lista de idiomas hablados en el país.
  final List<String> capital; // Lista de capitales del país.
  final int population; // Población del país.
  final String region; // Región geográfica del país.
  final String subregion; // Subregión geográfica del país.
  final List<String> borders; // Lista de países limítrofes.
  final List<String> currencies; // Lista de monedas utilizadas en el país.

  Pais({
    required this.oficialName,
    required this.name,
    required this.flag,
    required this.code,
    required this.id,
    required this.languages,
    required this.capital,
    required this.population,
    required this.region,
    required this.subregion,
    required this.borders,
    required this.currencies,
  });
}

// Mock 8 países de África
var paisesAfrica = <Pais>[
  Pais(
    oficialName: 'Argelia',
    name: 'Argelia',
    flag: '🇩🇿',
    code: 'ALG',
    id: 12,
    languages: ['Arabic'],
    capital: ['Algiers'],
    population: 40400000,
    region: 'Africa',
    subregion: 'Northern Africa',
    borders: ['TUN', 'LBY', 'NER', 'ESH', 'MRT', 'MLI', 'MAR'],
    currencies: ['Algerian dinar'],
  ),
  Pais(
    oficialName: 'Camerún',
    name: 'Camerún',
    flag: '🇨🇲',
    code: 'CMR',
    id: 120,
    languages: ['English', 'French'],
    capital: ['Yaoundé'],
    population: 22709892,
    region: 'Africa',
    subregion: 'Middle Africa',
    borders: ['CAF', 'TCD', 'COG', 'GNQ', 'GAB', 'NGA'],
    currencies: ['Central African CFA franc'],
  ),
  Pais(
    oficialName: 'Chad',
    name: 'Chad',
    flag: '🇹🇩',
    code: 'CHA',
    id: 148,
    languages: ['Arabic', 'French'],
    capital: ['N\'Djamena'],
    population: 14497000,
    region: 'Africa',
    subregion: 'Middle Africa',
    borders: ['CMR', 'CAF', 'LBY', 'NER', 'NGA', 'SSD', 'SDN'],
    currencies: ['Central African CFA franc'],
  ),
  Pais(
    oficialName: 'Congo (Rep. Dem.)',
    name: 'Congo (Rep. Dem.)',
    flag: '🇨🇩',
    code: 'COD',
    id: 180,
    languages: ['French', 'Kikongo', 'Lingala', 'Tshiluba', 'Swahili'],
    capital: ['Kinshasa'],
    population: 85026000,
    region: 'Africa',
    subregion: 'Middle Africa',
    borders: ['AGO', 'BDI', 'CAF', 'COG', 'RWA', 'SSD', 'TAN', 'UGA', 'ZMB'],
    currencies: ['Congolese franc'],
  ),
  Pais(
    oficialName: 'Djibouti',
    name: 'Djibouti',
    flag: '🇩🇯',
    code: 'DJI',
    id: 262,
    languages: ['Arabic', 'French'],
    capital: ['Djibouti'],
    population: 900000,
    region: 'Africa',
    subregion: 'Eastern Africa',
    borders: ['ERI', 'ETH', 'SOM'],
    currencies: ['Djiboutian franc'],
  ),
  Pais(
    oficialName: 'Eritrea',
    name: 'Eritrea',
    flag: '🇪🇷',
    code: 'ERI',
    id: 232,
    languages: ['Arabic', 'English', 'Tigrinya'],
    capital: ['Asmara'],
    population: 5352000,
    region: 'Africa',
    subregion: 'Eastern Africa',
    borders: ['DJI', 'ETH', 'SDN'],
    currencies: ['Eritrean nakfa'],
  ),
  Pais(
    oficialName: 'Nigeria',
    name: 'Nigeria',
    flag: '🇳🇬',
    code: 'NGR',
    id: 566,
    languages: ['English'],
    capital: ['Abuja'],
    population: 186988000,
    region: 'Africa',
    subregion: 'Western Africa',
    borders: ['BEN', 'CMR', 'TCD', 'NER'],
    currencies: ['Nigerian naira'],
  ),
  Pais(
    oficialName: 'Ruanda',
    name: 'Ruanda',
    flag: '🇷🇼',
    code: 'RWA',
    id: 646,
    languages: ['English', 'French', 'Kinyarwanda'],
    capital: ['Kigali'],
    population: 12208407,
    region: 'Africa',
    subregion: 'Eastern Africa',
    borders: ['UGA', 'TZA', 'BDI', 'COD'],
    currencies: ['Rwandan franc'],
  )
];

// Mock 8 países de América
var paisesAmerica = <Pais>[
  Pais(
    oficialName: 'República Argentina',
    name: 'Argentina',
    flag: '🇦🇷',
    code: 'ARG',
    id: 32,
    languages: ['Guaraní', 'Spanish'],
    capital: ['Buenos Aires'],
    population: 45376763,
    region: 'Americas',
    subregion: 'South America',
    borders: ['BOL', 'BRA', 'CHL', 'PRY', 'URY'],
    currencies: ['Argentine peso'],
  ),
  Pais(
    oficialName: 'Estado Plurinacional de Bolivia',
    name: 'Bolivia',
    flag: '🇧🇴',
    code: 'BOL',
    id: 68,
    languages: ['Aymara', 'Guaraní', 'Quechua', 'Spanish'],
    capital: ['Sucre'],
    population: 11673029,
    region: 'Americas',
    subregion: 'South America',
    borders: ['ARG', 'BRA', 'CHL', 'PRY', 'PER'],
    currencies: ['Bolivian boliviano'],
  ),
  Pais(
    oficialName: 'República Federativa del Brasil',
    name: 'Brasil',
    flag: '🇧🇷',
    code: 'BRA',
    id: 76,
    languages: ['Portuguese'],
    capital: ['Brasília'],
    population: 212559409,
    region: 'Americas',
    subregion: 'South America',
    borders: [
      'ARG',
      'BOL',
      'COL',
      'GUF',
      'GUY',
      'PRY',
      'PER',
      'SUR',
      'URY',
      'VEN'
    ],
    currencies: ['Brazilian real'],
  ),
  Pais(
    oficialName: 'República de Colombia',
    name: 'Colombia',
    flag: '🇨🇴',
    code: 'COL',
    id: 170,
    languages: ['Spanish'],
    capital: ['Bogotá'],
    population: 50882884,
    region: 'Americas',
    subregion: 'South America',
    borders: ['BRA', 'ECU', 'PAN', 'PER', 'VEN'],
    currencies: ['Colombian peso'],
  ),
  Pais(
    oficialName: 'República del Ecuador',
    name: 'Ecuador',
    flag: '🇪🇨',
    code: 'ECU',
    id: 218,
    languages: ['Spanish'],
    capital: ['Quito'],
    population: 17643060,
    region: 'Americas',
    subregion: 'South America',
    borders: ['COL', 'PER'],
    currencies: ['United States dollar'],
  ),
  Pais(
    oficialName: 'Estados Unidos de América',
    name: 'Estados Unidos',
    flag: '🇺🇸',
    code: 'USA',
    id: 840,
    languages: ['English'],
    capital: ['Washington, D.C.'],
    population: 329484123,
    region: 'Americas',
    subregion: 'North America',
    borders: ['CAN', 'MEX'],
    currencies: ['United States dollar'],
  ),
  Pais(
    oficialName: 'Estados Unidos Mexicanos',
    name: 'México',
    flag: '🇲🇽',
    code: 'MEX',
    id: 484,
    languages: ['Spanish'],
    capital: ['Mexico City'],
    population: 128932753,
    region: 'Americas',
    subregion: 'North America',
    borders: ['BLZ', 'GTM', 'USA'],
    currencies: ['Mexican peso'],
  ),
  Pais(
    oficialName: 'República de Panamá',
    name: 'Panamá',
    flag: '🇵🇦',
    code: 'PAN',
    id: 591,
    languages: ['Spanish'],
    capital: ['Panama City'],
    population: 4314768,
    region: 'Americas',
    subregion: 'Central America',
    borders: ['COL', 'CRI'],
    currencies: ['Panamanian balboa', 'United States dollar'],
  ),
];

// Clase que representa una versión simplificada de la información de un país.
class PaisSimplify {
  final String oficialName; // Nombre oficial del país.
  final String flag; // Bandera del país.
  final List<String> capital; // Lista de capitales del país.

  PaisSimplify({
    required this.oficialName,
    required this.flag,
    required this.capital,
  });
}
