name: proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/america.png
    - assets/africa.png
  fonts:
      - family: Jost
        fonts:
          - asset: fonts/Jost-Regular.ttf
            weight: 400
          - asset: fonts/Jost-SemiBold.ttf
            weight: 600
          - asset: fonts/Jost-Bold.ttf
            weight: 700