name: proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^3.0.1
  intl: ^0.18.1
  animate_do: ^3.1.2
  http: ^1.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/america.png
    - assets/africa.png
  fonts:
      - family: Jost
        fonts:
          - asset: assets/fonts/Jost-Regular.ttf
            weight: 400
          - asset: assets/fonts/Jost-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Jost-Bold.ttf
            weight: 700